config/routes.rb
MakerSource::Application.routes.draw do
  authenticated :user do
    root :to => 'projects#index'
  end
  root :to => "projects#index"
  devise_for :users
    
    match '/users/:user_id/messages/inbox(/:id(.:format))', :controller => 'messages', :action => 'inbox', :via => [:get], :as => 'user_messages_inbox'
    match '/users/:user_id/messages/drafts(/:id(.:format))', :controller => 'messages', :action => 'drafts', :via => [:get], :as => 'user_messages_drafts'
    match '/users/:user_id/messages/sent(/:id(.:format))', :controller => 'messages', :action => 'sent', :via => [:get], :as => 'user_messages_sent'
    match '/users/:user_id/messages/archive(/:id(.:format))', :controller => 'messages', :action => 'archive', :via => [:get], :as => 'user_messages_archive'
    match '/users/:user_id/messages/trash(/:id(.:format))', :controller => 'messages', :action => 'trash', :via => [:get], :as => 'user_messages_trash'
    
    resources :users do
        resources :messages
        resources :contacts
    end
    resources :projects do
        resources :assets
        resources :tasks
    end
end

app/models/message.rb
class Message < ActiveRecord::Base
    belongs_to :user
    
    attr_accessible :content, :from_user_id, :title, :to_user_id, :name, :folder, :sent, :thread_count, :parent_id, :created_at, :updated_at
    
    validates :content,  :presence => true,
    :length => { :minimum => 3 }
    validates :from_user_id,  :presence => true
    validates :title, :presence => true,
    :length => { :minimum => 3 }
    validates :to_user_id,  :presence => true
    
    def from_name
        fn = User.find(self.from_user_id).first_name 
        ln = User.find(self.from_user_id).last_name
        from_name ="#{fn} #{ln}"
    end
    
    def to_name
        fn = User.find(self.to_user_id).first_name 
        ln = User.find(self.to_user_id).last_name
        to_name ="#{fn} #{ln}"
    end
    
    def return_time
    self.updated_at.in_time_zone('Hawaii').to_formatted_s(:long_ordinal)
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
    # GET user/:user_id/messages
    # GET user/:user_id/messages.json
    def index
        @user = User.find(params[:user_id])
        @message = @user.messages.all
        #@message = @message.paginate(:page => params[:page], :per_page => 9)
        respond_to do |format|
            format.html # index.html.erb
            format.json { render json: user_messages_path(@user) }
        end
    end

  # GET user/:user_id/messages/1
  # GET user/:user_id/messages/1.json
  def show
      @user = User.find(params[:user_id])
      @message = @user.messages.find(params[:id])
      @message.update_attribute(:read, true)
        respond_to do |format|
            format.html # index.html.erb
            format.json { render json: user_messages_path(@user) }
        end
  end

  # GET user/:user_id/messages/new
  # GET user/:user_id/messages/new.json
  def new
      @user = User.find(params[:user_id])
      @message = @user.messages.new
  end

  # GET user/:user_id/messages/1/edit
  def edit
      @user = User.find(params[:user_id])
      @message = @user.messages.find(params[:id])  
  end
  
  # GET user/:user_id/messages/inbox/1
  def inbox
      @user = User.find(params[:user_id])
      @message = @user.messages.find(params[:id])  
      @message.folder = "inbox"  
      respond_to do |format|
          if @message.save
              format.html { redirect_to :back, notice: 'Message was successfully moved to inbox.' }
              format.json { head :no_content }
              else
              #format.html { render action: "new" }
              format.html { redirect_to :back, alert: 'Message was unsuccessfully moved to inbox.' }
              format.json { render json: @message.errors, status: :unprocessable_entity}
          end
      end
  end
    
  def sent
        @user = User.find(params[:user_id])
        @message = @user.messages.all 
          respond_to do |format|
            format.html # index.html.erb
            format.json { render json: user_messages_path(@user) }
        end
  end
    
  def drafts
      @user = User.find(params[:user_id])
      @message = @user.messages.build(params[:message])
      @message.sent = false
      @message.folder = "drafts"  
      respond_to do |format|
            format.html # index.html.erb
            format.json { render json: user_messages_path(@user) }
      end
  end
  
  # GET user/:user_id/messages/archive
  # GET user/:user_id/messages/archive/1
  def archive
      @user = User.find(params[:user_id])
      @message = @user.messages.find(params[:id])  
      @message.folder = "archive"  
      respond_to do |format|
          if @message.save
              format.html { redirect_to :back, notice: 'Message was successfully archived.' }
              format.json { head :no_content }
              else
              #format.html { render action: "new" }
              format.html { redirect_to user_messages_path(@user), alert: 'Message was unsuccessfully archived.' }
              format.json { render json: @message.errors, status: :unprocessable_entity}
          end
      end
  end
  
  # GET user/:user_id/messages/trash
  # GET user/:user_id/messages/trash/1
  def trash
      @user = User.find(params[:user_id])
      @message = @user.messages.find(params[:id])  
      @message.folder = "trash"  
      respond_to do |format|
          if @message.save
              format.html { redirect_to :back, notice: 'Message was successfully moved to trash.' }
              format.json { head :no_content }
              else
              #format.html { render action: "new" }
              format.html { redirect_to user_messages_path(@user), alert: 'Message was unsuccessfully moved to trash.' }
              format.json { render json: @message.errors, status: :unprocessable_entity}
          end
      end
  end

  # POST user/:user_id/messages
  # POST user/:user_id/messages.json
  def create
      if params[:save_button]
      @user = User.find(params[:user_id])
      @message = @user.messages.build(params[:message])
      @message.folder = "drafts"
        respond_to do |format|
          if @message.save
              format.html { redirect_to user_messages_drafts_path(@user), notice: 'Message was successfully saved.' }
              format.json { head :no_content }
              else
              format.html { redirect_to user_messages_path(@user), alert: 'Message was unsuccessfully saved.' }
              format.json { render json: @message.errors, status: :unprocessable_entity}
          end
        end
      else 
      @sender = User.find(params[:user_id])
      @message_sent = @sender.messages.build(params[:message])
      @message_sent.folder = "sent"
      @contact = @sender.contacts.where(:contact_name => params[:message][:name]).first
      if @contact.present? || params[:message][:to_user_id].present?
      if @contact.present?
      @message_sent.to_user_id = @contact.contact_id
      @recipient = User.find(@message_sent.to_user_id)
      @message_recieved = @recipient.messages.build(params[:message])
      @message_recieved.to_user_id = @contact.contact_id
      else
      @message_sent.to_user_id = params[:message][:to_user_id]
      @recipient = User.find(@message_sent.to_user_id)
      @message_recieved = @recipient.messages.build(params[:message])
      @message_recieved.to_user_id = params[:message][:to_user_id]
      end
      @message_recieved.thread_count = @message_sent.thread_count
      @message_recieved.folder = "inbox"
      if !@recipient.contacts.where(:contact_id => @sender.id).first.present?
      @new_contact = @recipient.contacts.build(:contact_name => @sender.name, :contact_id => @sender.id, :user_id => @recipient.id)
      @new_contact.save
      end
      end
    respond_to do |format|
      if @message_sent.save && @message_recieved.save
        if @message_sent.thread_count == 0
        @message_sent.update_attribute(:parent_id, @message_sent.id)
        @message_recieved.update_attribute(:parent_id, @message_sent.id)
        end
        format.html { redirect_to user_messages_path(@sender), notice: 'Message was successfully created.' }
        #format.json { render json: @message, status: :created, location: @message }
        format.json { head :no_content }
      else
        #format.html { render action: "new" }
        format.html { redirect_to user_messages_path(@sender), alert: 'Message was unsuccessfully created.' }
        format.json { render json: @message_sent.errors, status: :unprocessable_entity}
      end
    end
    end
  end
    
  # PUT user/:user_id/messages/1
  # PUT user/:user_id/messages/1.json
  def update
    if params[:send_button]
      @sender = User.find(params[:user_id])
      @message_sent = @sender.messages.find(params[:id])
      @message_sent.folder = "sent"
      @contact = @sender.contacts.where(:contact_name => params[:message][:name]).first
      if @contact.present? || params[:message][:to_user_id].present?
      if @contact.present?
      @message_sent.to_user_id = @contact.contact_id
      @recipient = User.find(@message_sent.to_user_id)
      @message_recieved = @recipient.messages.build(params[:message])
      @message_recieved.to_user_id = @contact.contact_id
      else
      @message_sent.to_user_id = params[:message][:to_user_id]
      @recipient = User.find(@message_sent.to_user_id)
      @message_recieved = @recipient.messages.build(params[:message])
      @message_recieved.to_user_id = params[:message][:to_user_id]
      end
      @message_recieved.thread_count = @message_sent.thread_count
      @message_recieved.folder = "inbox"
      if !@recipient.contacts.where(:contact_id => @sender.id).first.present?
      @new_contact = @recipient.contacts.build(:contact_name => @sender.name, :contact_id => @sender.id, :user_id => @recipient.id)
      @new_contact.save
      end
      end
      respond_to do |format|
        if @message_sent.update_attributes(params[:message]) && 
        @message_recieved.update_attributes(params[:message]) && 
        @message_sent.save && @message_recieved.save
        if @message_sent.thread_count == 0
        @message_sent.update_attribute(:parent_id, @message_sent.id)
        @message_recieved.update_attribute(:parent_id, @message_sent.id)
        else
        @message_recieved.update_attribute(:parent_id, @message_sent.parent_id)
        end
        format.html { redirect_to user_messages_path(@sender), notice: 'Message was successfully created.' }
        #format.json { render json: @message, status: :created, location: @message }
        format.json { head :no_content }
        else
        #format.html { render action: "new" }
        format.html { redirect_to user_messages_path(@sender), alert: 'Message was unsuccessfully created.' }
        format.json { render json: @message_sent.errors, status: :unprocessable_entity}
        end
    end
      
    else
      @user = User.find(params[:user_id])
      @message = @user.messages.find(params[:id])    
    respond_to do |format|
      if @message.update_attributes(params[:message])
        format.html { redirect_to user_messages_drafts_path(@user), notice: 'Message was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
    end
  end

  # DELETE user/:user_id/messages/1
  # DELETE user/:user_id/messages/1.json
  def destroy
      @user = User.find(params[:user_id])
      @message = @user.messages.find(params[:id])
      @message.destroy

    respond_to do |format|
      format.html { redirect_to user_messages_path(@users) }
      format.json { head :no_content }
    end
  end
end

app/views/messages/_form_edit.html.erb
<%= simple_form_for([@user, @message]) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.hidden_field :to_user_id %>
    <%= f.hidden_field :from_user_id, :value => @user.id %>
    <%= f.input :title %>
    <%= f.input :content %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
    <%= f.button :submit, 'Send', :name => 'send_button' %>

  </div>
<% end %>

app/views/messages/_form_new.html.erb
   
<%= simple_form_for([@user, @message]) do |f| %>
  <%= f.error_notification %>
  <div class="row">
  <div class="span1" id="form-labels">
    <p style="margin-top:5px;">User ID: </p>
    <p style="margin-top:28px;">Subject: </p>
  </div>

  <div class="span9">
  <div class="form-inputs">
    <%= f.input :to_user_id, :label => false, :input_html => 
    { :style => 'width: 478px'} %>
    <%= f.hidden_field :from_user_id, :value => @user.id %>
    <%= f.input :title, :label => false, :input_html => 
    { :style => 'width: 478px'} %>
    <%= f.input :content, :label => false, :as => :text, :input_html => 
    { :style => 'width: 478px', :rows => 12 } %>
    <%= f.hidden_field :thread_count, :value => 0 %>
  </div>

  <div class="form-actions">
    <%= link_to 'Cancel', user_messages_path(@user), :class => 'btn'%>
    <%= f.button :submit, 'Save', :name => 'save_button' %>
    <%= f.button :submit %>
  </div>
  </div>
  </div>
<% end %>

app/views/messages/_form_profile_contact.html.erb
        <%= simple_form_for([current_user, current_user.messages.new]) do |f| %>
        <%= f.error_notification %>

        <div class="form-inputs">
        <%= f.hidden_field :to_user_id, :value => @user.id %>
        <p> From: <%= current_user.name %> </p>
        <%= f.hidden_field :from_user_id, :value => current_user.id %>
        <%= f.input :title %>
        <%= f.hidden_field :thread_count, :value => 0 %>
        <%= f.input :content %>
        </div>
  
        <div class="form-actions">
        <%= f.button :submit, 'Save', :name => 'save_button' %>
        <%= f.button :submit %>  
        </div>
        <% end %>

app/views/messages/_response.html.erb
<%= render 'response_form' %>

app/views/messages/archive.html.erb
<!-- This is the user inbox. -->
<div class="white-background">
<div class="row-fluid">
<div class="span3" >
    <div class="nav messages-sidenav" >    
        <ul class="nav-list">
          <li><div class="compose"><button class="btn btn-block" type="button"><%= link_to 'Compose Message', new_user_message_path(@user) %></button></div></li>
          <li class="divider-horizontal"></li>
          <li><%= link_to 'Inbox', user_messages_path(@user) %></li>
          <li class="divider-horizontal"></li>
          <li><%= link_to 'Drafts', user_messages_drafts_path(@user) %></li>
          <li class="divider-horizontal"></li>
          <li><%= link_to 'Sent', user_messages_sent_path(@user)  %></li>
          <li class="divider-horizontal"></li>
          <li class="active"><%= link_to 'Archive', user_messages_archive_path(@user)  %></li>
          <li class="divider-horizontal"></li>
          <li><%= link_to 'Trash', user_messages_trash_path(@user)  %></li>
          <li class="divider-horizontal"></li>
          <li class="center-align"><%= link_to 'View Contacts', user_contacts_path(@user) %></li>
        </ul>
    </div>
</div>
<div class="span9">
<h1>Welcome to Your Archives Folder</h1>
</br>
<table class="table">
  <tr>
    <th>Status</th>
    <th>From name</th>
    <th>Title</th>
    <th>Date</th>
    <th></th>
    <th></th>
  </tr>

<% @user = current_user %>
<% @distinct_messages = @user.messages.select("DISTINCT(PARENT_ID)") %>
<% @messages_in_folder = Array.new%>
<% @distinct_messages.each do |m| %>
<% @messages = @user.messages.find(:all, :conditions => {:parent_id => m.parent_id}) %>
<% @messages_sorted = @messages.sort_by(&:thread_count).reverse %>
<% @messages_sorted.each do |m| %>
<% if m.folder == "archive" %>
<% @messages_in_folder << m%>
<% break %>
<% end %>
<% end %>
<% end %>
<% @mif = @messages_in_folder.sort_by(&:created_at).reverse %>
<% @mif.each do |message| %>
  <tr>
    <% if message.read %>
    <td>Read</td>
    <% else %>
    <td>Unread</td>
    <% end %>
    <td><%= message.from_user_id %></td>
    <td><%= link_to message.title,  user_message_path(@user, message) %></td>
    <td><%= message.return_time %></td>
    <td><%= link_to 'Return to Inbox', {:controller => 'messages', :action => 'inbox', :id => message.id} %></td>
    <td><%= link_to 'Trash', {:controller => 'messages', :action => 'trash', :id => message.id} %></td>
  </tr>
<% end %>
</table>

<br />

</div>
</div>
</div>

app/views/messages/drafts.html.erb
<!-- This is the user inbox. -->
<div class="white-background">
<div class="row-fluid">
<div class="span3" >
    <div class="nav messages-sidenav" >    
        <ul class="nav-list">
          <li><div class="compose"><button class="btn btn-block" type="button"><%= link_to 'Compose Message', new_user_message_path(@user) %></button></div></li>
          <li class="divider-horizontal"></li>
          <li><%= link_to 'Inbox', user_messages_path(@user) %></li>
          <li class="divider-horizontal"></li>
          <li class="active"><%= link_to 'Drafts', user_messages_drafts_path(@user) %></li>
          <li class="divider-horizontal"></li>
          <li><%= link_to 'Sent', user_messages_sent_path(@user)  %></li>
          <li class="divider-horizontal"></li>
          <li><%= link_to 'Archive', user_messages_archive_path(@user)  %></li>
          <li class="divider-horizontal"></li>
          <li><%= link_to 'Trash', user_messages_trash_path(@user)  %></li>
          <li class="divider-horizontal"></li>
          <li class="center-align"><%= link_to 'View Contacts', user_contacts_path(@user) %></li>
        </ul>
    </div>
</div>
<div class="span9">
<h1>Welcome to Your Drafts Folder</h1>
</br>
<table class="table">
  <tr>
    <th>To name</th>
    <th>Title</th>
    <th></th>
  </tr>

<% @user = current_user %>
<% @messages_in_folder = @user.messages.sort_by(&:updated_at).reverse %>
<% @messages_in_folder.each do |message| %>
<% if message.folder == "drafts" %>
  <tr>
    <td><%= message.to_user_id %></td>
    <td><%= link_to message.title,  edit_user_message_path(@user, message) %></td>
    <td><%= link_to 'Edit', edit_user_message_path(@user, message) %> | <%= link_to 'Delete', [message.user, message], method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
<% end %>
</table>

<br />

</div>
</div>
</div>

app/views/messages/edit.html.erb
<!-- This is where messages are edited. Only used if messages are saved as drafts. -->
<div class="white-background">
<div class="row-fluid">
<div class="span3" >
    <div class="nav messages-sidenav" >    
        <ul class="nav-list">
          <li><div class="compose"><button class="btn btn-block" type="button"><%= link_to 'Compose Message', new_user_message_path(@user) %></button></div></li>
          <li class="divider-horizontal"></li>
          <li><%= link_to 'Inbox', user_messages_path(@user) %></li>
          <li class="divider-horizontal"></li>
          <li class="active"><%= link_to 'Drafts', user_messages_drafts_path(@user) %></li>
          <li class="divider-horizontal"></li>
          <li><%= link_to 'Sent', user_messages_sent_path(@user)  %></li>
          <li class="divider-horizontal"></li>
          <li><%= link_to 'Archive', user_messages_archive_path(@user)  %></li>
          <li class="divider-horizontal"></li>
          <li><%= link_to 'Trash', user_messages_trash_path(@user)  %></li>
          <li class="divider-horizontal"></li>
          <li class="active center-align"><%= link_to 'View Contacts', user_contacts_path(@user) %></li>
        </ul>
    </div>
</div>
<div class="span9">
<h1>Editing Draft Message</h1>

<%= render 'form_edit' %>

</div>
</div>
</div>

app/views/messages/index.html.erb
<!-- This is the user inbox. -->
<div class="white-background">
<div class="row-fluid">
<div class="span3" >
    <div class="nav messages-sidenav" >    
        <ul class="nav-list">
          <li><div class="compose"><button class="btn btn-block" type="button"><%= link_to 'Compose Message', new_user_message_path(@user) %></button></div></li>
          <li class="divider-horizontal"></li>
          <li class="active"><%= link_to 'Inbox', user_messages_path(@user) %></li>
          <li class="divider-horizontal"></li>
          <li><%= link_to 'Drafts', user_messages_drafts_path(@user) %></li>
          <li class="divider-horizontal"></li>
          <li><%= link_to 'Sent', user_messages_sent_path(@user)  %></li>
          <li class="divider-horizontal"></li>
          <li><%= link_to 'Archive', user_messages_archive_path(@user)  %></li>
          <li class="divider-horizontal"></li>
          <li><%= link_to 'Trash', user_messages_trash_path(@user)  %></li>
          <li class="divider-horizontal"></li>
          <li class="center-align"><%= link_to 'View Contacts', user_contacts_path(@user) %></li>
        </ul>
    </div>
</div>
<div class="span9">
<h1>Welcome to Your Message Center</h1>
</br>
<table class="table">
  <tr>
    <th>Status</th>
    <th>From name</th>
    <th>Title</th>
    <th>Date</th>
    <th></th>
    <th></th>
  </tr>

<% @user = current_user %>
<% @distinct_messages = @user.messages.select("DISTINCT(PARENT_ID)") %>
<% @messages_in_folder = Array.new%>
<% @distinct_messages.each do |m| %>
<% @messages = @user.messages.find(:all, :conditions => {:parent_id => m.parent_id}) %>
<% @messages_sorted = @messages.sort_by(&:thread_count).reverse %>
<% @messages_sorted.each do |m| %>
<% if m.folder == "inbox" %>
<% @messages_in_folder << m%>
<% break %>
<% end %>
<% end %>
<% end %>
<% @mif = @messages_in_folder.sort_by(&:updated_at).reverse %>
<% @mif.each do |message| %>
  <tr>
    <% if message.read %>
    <td>Read</td>
    <% else %>
    <td>Unread</td>
    <% end %>
    <td><%= message.from_user_id %></td>
    <td><%= link_to message.title,  user_message_path(@user, message) %></td>
    <td><%= message.return_time %></td>
    <td><%= link_to 'Archive', {:controller => 'messages', :action => 'archive', :id => message.id} %></td>
    <td><%= link_to 'Trash', {:controller => 'messages', :action => 'trash', :id => message.id} %></td>
  </tr>
<% end %>
</table>

<br />

</div>
</div>
</div>

app/views/messages/new.html.erb
<!-- This is where we create new messages or responses. -->
<div class="white-background">
<div class="row-fluid">
<div class="span3" >
    <div class="nav messages-sidenav" >    
        <ul class="nav-list">
          <li><div class="compose"><button class="btn btn-block" type="button"><%= link_to 'Compose Message', new_user_message_path(@user) %></button></div></li>
          <li class="divider-horizontal"></li>
          <li><%= link_to 'Inbox', user_messages_path(@user) %></li>
          <li class="divider-horizontal"></li>
          <li><%= link_to 'Drafts', user_messages_drafts_path(@user) %></li>
          <li class="divider-horizontal"></li>
          <li><%= link_to 'Sent', user_messages_sent_path(@user)  %></li>
          <li class="divider-horizontal"></li>
          <li><%= link_to 'Archive', user_messages_archive_path(@user)  %></li>
          <li class="divider-horizontal"></li>
          <li><%= link_to 'Trash', user_messages_trash_path(@user)  %></li>
          <li class="divider-horizontal"></li>
          <li class="center-align"><%= link_to 'View Contacts', user_contacts_path(@user) %></li>
        </ul>
    </div>
</div>
<div class="span9">
<h1>New message</h1>
<% @user = current_user %>

<%= render 'form_new' %>

</div>
</div>
</div>

app/views/messages/sent.html.erb
<!-- This is the user inbox. -->
<div class="white-background">
<div class="row-fluid">
<div class="span3" >
    <div class="nav messages-sidenav" >    
        <ul class="nav-list">
          <li><div class="compose"><button class="btn btn-block" type="button"><%= link_to 'Compose Message', new_user_message_path(@user) %></button></div></li>
          <li class="divider-horizontal"></li>
          <li><%= link_to 'Inbox', user_messages_path(@user) %></li>
          <li class="divider-horizontal"></li>
          <li><%= link_to 'Drafts', user_messages_drafts_path(@user) %></li>
          <li class="divider-horizontal"></li>
          <li class="active"><%= link_to 'Sent', user_messages_sent_path(@user)  %></li>
          <li class="divider-horizontal"></li>
          <li><%= link_to 'Archive', user_messages_archive_path(@user)  %></li>
          <li class="divider-horizontal"></li>
          <li><%= link_to 'Trash', user_messages_trash_path(@user)  %></li>
          <li class="divider-horizontal"></li>
          <li class="center-align"><%= link_to 'View Contacts', user_contacts_path(@user) %></li>
        </ul>
    </div>
</div>
<div class="span9">
<h1>Welcome to Your Sent Folder</h1>
</br>
<table class="table">
  <tr>
    <th>To name</th>
    <th>Title</th>
    <th>Date</th>
    <th></th>
  </tr>

<% @user = current_user %>
<% @messages_in_folder = @user.messages.sort_by(&:updated_at).reverse %>
<% @messages_in_folder.each do |message| %>
<% if message.folder == "sent" %>
  <tr>
    <td><%= message.to_user_id %></td>
    <td><%= link_to message.title,  user_message_path(@user, message) %></td>
    <td><%= message.return_time %></td>
    <td><%= link_to 'Delete', [message.user, message], method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>

<% end %>
</table>

<br />

</div>
</div>
</div>

app/views/messages/trash.html.erb
<!-- This is the user inbox. -->
<div class="white-background">
<div class="row-fluid">
<div class="span3" >
    <div class="nav messages-sidenav" >    
        <ul class="nav-list">
          <li><div class="compose"><button class="btn btn-block" type="button"><%= link_to 'Compose Message', new_user_message_path(@user) %></button></div></li>
          <li class="divider-horizontal"></li>
          <li><%= link_to 'Inbox', user_messages_path(@user) %></li>
          <li class="divider-horizontal"></li>
          <li><%= link_to 'Drafts', user_messages_drafts_path(@user) %></li>
          <li class="divider-horizontal"></li>
          <li><%= link_to 'Sent', user_messages_sent_path(@user)  %></li>
          <li class="divider-horizontal"></li>
          <li><%= link_to 'Archive', user_messages_archive_path(@user)  %></li>
          <li class="divider-horizontal"></li>
          <li class="active"><%= link_to 'Trash', user_messages_trash_path(@user)  %></li>
          <li class="divider-horizontal"></li>
          <li class="center-align"><%= link_to 'View Contacts', user_contacts_path(@user) %></li>
        </ul>
    </div>
</div>
<div class="span9">
<h1>Welcome to Your Trash Folder</h1>
</br>
<table class="table">
  <tr>
    <th>From name</th>
    <th>Title</th>
    <th>Date</th>
    <th></th>
  </tr>

<% @user = current_user %>
<% @distinct_messages = @user.messages.select("DISTINCT(PARENT_ID)") %>
<% @messages_in_folder = Array.new%>
<% @distinct_messages.each do |m| %>
<% @messages = @user.messages.find(:all, :conditions => {:parent_id => m.parent_id}) %>
<% @messages_sorted = @messages.sort_by(&:thread_count).reverse %>
<% @messages_sorted.each do |m| %>
<% if m.folder == "trash" %>
<% @messages_in_folder << m%>
<% break %>
<% end %>
<% end %>
<% end %>
<% @mif = @messages_in_folder.sort_by(&:created_at).reverse %>
<% @mif.each do |message| %>
  <tr>
    <td><%= message.from_user_id%></td>
    <td><%= link_to message.title,  user_message_path(@user, message) %></td>
    <td><%= message.return_time %></td>
    <td><%= link_to 'Return to Archives', {:controller => 'messages', :action => 'archive', :id => message.id} %></td>
    <td><%= link_to 'Delete', [message.user, message], method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

</div>
</div>
</div>