config/routes.rb
MakerSource::Application.routes.draw do
  authenticated :user do
    root :to => 'projects#index'
  end
  root :to => "projects#index"
  devise_for :users
    
    match '/users/:user_id/messages/inbox(/:id(.:format))', :controller => 'messages', :action => 'inbox', :via => [:get], :as => 'user_messages_inbox'
    match '/users/:user_id/messages/drafts(/:id(.:format))', :controller => 'messages', :action => 'drafts', :via => [:get], :as => 'user_messages_drafts'
    match '/users/:user_id/messages/sent(/:id(.:format))', :controller => 'messages', :action => 'sent', :via => [:get], :as => 'user_messages_sent'
    match '/users/:user_id/messages/archive(/:id(.:format))', :controller => 'messages', :action => 'archive', :via => [:get], :as => 'user_messages_archive'
    match '/users/:user_id/messages/trash(/:id(.:format))', :controller => 'messages', :action => 'trash', :via => [:get], :as => 'user_messages_trash'
    
    resources :users do
        resources :messages
        resources :contacts
    end
    resources :projects do
        resources :assets
        resources :tasks
    end
end

app/models/contact.rb
class Contact < ActiveRecord::Base
    belongs_to :user
  attr_accessible :contact_id, :contact_name, :user_id
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
    
    def destroy
        @user = User.find(params[:user_id])
        @contact = @user.contacts.find(params[:id])
        @contact.destroy
        
        respond_to do |format|
            format.html { redirect_to user_contacts_path(@user) }
            format.json { head :no_content }
        end
    end
end

app/views/contacts/index.html.erb
<!-- This is the user inbox. -->
<% @user = current_user %>
<div class="white-background">
<div class="row-fluid">
<div class="span3" >
    <div class="nav messages-sidenav" >    
        <ul class="nav-list">
          <li><div class="compose"><button class="btn btn-block" type="button"><%= link_to 'Compose Message', new_user_message_path(@user) %></button></div></li>
          <li class="divider-horizontal"></li>
          <li><%= link_to 'Inbox', user_messages_path(@user) %></li>
          <li class="divider-horizontal"></li>
          <li><%= link_to 'Drafts', user_messages_drafts_path(@user) %></li>
          <li class="divider-horizontal"></li>
          <li><%= link_to 'Sent', user_messages_sent_path(@user)  %></li>
          <li class="divider-horizontal"></li>
          <li><%= link_to 'Archive', user_messages_archive_path(@user)  %></li>
          <li class="divider-horizontal"></li>
          <li><%= link_to 'Trash', user_messages_trash_path(@user)  %></li>
        </ul>
    </div>
</div>
<div class="span9">
<h1>Contacts List</h1>
<% if @user.contacts.present? %>
<% @user.contacts.each do | contact | %>
<p> <%= link_to contact.contact_name, user_path(User.find(contact.contact_id)) %>    | <%= link_to "Remove", [contact.user, contact], method: :delete, data: { confirm: 'Are you sure?' } %></p>
<% end %>
<% end %>
</div>
</div>
</div>