config/routes.rb
MakerSource::Application.routes.draw do
  authenticated :user do
    root :to => 'projects#index'
  end
  root :to => "projects#index"
  devise_for :users
    
    match '/users/:user_id/messages/inbox(/:id(.:format))', :controller => 'messages', :action => 'inbox', :via => [:get], :as => 'user_messages_inbox'
    match '/users/:user_id/messages/drafts(/:id(.:format))', :controller => 'messages', :action => 'drafts', :via => [:get], :as => 'user_messages_drafts'
    match '/users/:user_id/messages/sent(/:id(.:format))', :controller => 'messages', :action => 'sent', :via => [:get], :as => 'user_messages_sent'
    match '/users/:user_id/messages/archive(/:id(.:format))', :controller => 'messages', :action => 'archive', :via => [:get], :as => 'user_messages_archive'
    match '/users/:user_id/messages/trash(/:id(.:format))', :controller => 'messages', :action => 'trash', :via => [:get], :as => 'user_messages_trash'
    
    resources :users do
        resources :messages
        resources :contacts
    end
    resources :projects do
        resources :assets
        resources :tasks
    end
end

app/models/project.rb
class Project < ActiveRecord::Base
    attr_accessible :name, :city, :continent, :country, :overview, :partner_organizations, :subject_tag, :moderator_id, :summary, :quote, :community_overview
    
    has_many :assets, :dependent => :destroy
    has_many :tasks, :dependent => :destroy
    
    attr_accessible :main_image, :community_image, :tech_image
    has_attached_file :main_image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
    has_attached_file :community_image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
    has_attached_file :tech_image, :styles => { :medium => "300x300>", :thumb => "100x100>" }


end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
    @projects = Project.all
      respond_to do |format|
          format.html # index.html.erb
          format.json { render json: @projects }
      end
  end

  def show
    @project = Project.find(params[:id])
      respond_to do |format|
          format.html # index.html.erb
          format.json { render json: @project }
      end
  end
    
  def new
    @project = Project.new
      respond_to do |format|
          format.html # index.html.erb
          format.json { render json: @project }
      end
  end

  def edit
      @project = Project.find(params[:id])
  end
    
    def create
        @project = Project.new(params[:project])
        
        respond_to do |format|
            if @project.save
                format.html { redirect_to @project, notice: 'Project was successfully created.' }
                format.json { render json: @project, status: :created, location: @project }
                else
                format.html { render action: "new" }
                format.json { render json: @project.errors, status: :unprocessable_entity }
            end
        end
    end

    def update
        @project = Project.find(params[:id])
        
        respond_to do |format|
            if @project.update_attributes(params[:project])
                format.html { redirect_to @project, notice: 'Project was successfully updated.' }
                format.json { head :no_content }
                else
                format.html { render action: "edit" }
                format.json { render json: @project.errors, status: :unprocessable_entity }
            end
        end
    end

    def destroy
        @project = Project.find(params[:id])
        @project.destroy
        
        respond_to do |format|
            format.html { redirect_to projects_url }
            format.json { head :no_content }
        end
    end
end

app/views/projects/_form.html.erb
<script>
  $(document).ready(function(){
  });
</script>

<%= simple_form_for(@project, :html => {:id => 'edit_project', :class => 'form-vertical', :multipart => true }) do |f| %>
  <%= f.error_notification %>
  <div class="form-inputs offset1">    
    <%=h f.input :name, :label => "Title", :input_html => { :style => 'width: 525px'} %>
    <div class="row" style="margin-left:-20px;">
    <div class="span4">
    <%=h f.input :city %></div>
    <div class="span1">
    <%= f.input :country %></div>
  </div>
    <%=h f.input :partner_organizations, :label => "Partners", :input_html => { :style => 'width: 525px'} %>
    <%=h f.input :summary, :label => "Summary", :input_html => { :style => 'width: 525px'} %>
    <%=h f.input :overview,  :as => :text, :label => "Problem Overview",
    :input_html => { :style => 'width: 525px', :rows => 12 }  %>
    <%= f.input :tech_image, :label => "Image of Technology" %>

    <%=h f.input :community_overview,  :as => :text, :label => "Community Description", :input_html => { :style => 'width: 525px', :rows => 12 }  %>
    <%=h f.input :quote,  :as => :string, :label => "Community Quote", :input_html => { :style => 'width: 525px', :rows => 12 }  %>
        <%= f.input :community_image, :label => "Community Image" %>

    <%=h f.input :subject_tag, :label => "Tags", :input_html => { :style => 'width: 525px'}
     %>
    <%=h f.input :moderator_id, :label => "Moderator", :input_html => { :style => 'width: 525px'}%>
    <%= f.input :main_image, :label => "Main Image" %>
  </div>

  <div class="form-actions">
    <span class="pull-right">
      <%= link_to 'Cancel', projects_path(), class: 'btn' %>
      <%= f.button :submit, class: 'btn btn-primary'%>
    </span>
  </div>
<% end %>

app/views/projects/edit.html.erb
<p id="notice"><%= notice %></p>
<div class="border offset2 span10" >
<h2 style="text-align:center;">Edit Project Details</h2>
<%= render 'form' %>
</div>

app/views/projects/index.html.erb
<h3 style="text-align:center;">Appropriate Technology Project Archive </h3>
<div class="border offset2 projects">
  <ul>
  <% @projects.each do |project| %>
    <li>
      <div class="span3">
        <%= image_tag project.main_image.url, :style => "margin:10px;margin-left:-20px;margin-bottom:20px;height:160px;width:200px;" %>
      </div>
      <p><%= link_to project.name, project %> added <%= project.created_at.to_date %></p>
      <%= project.summary %>
      <%= project.city if project.city %> <%= project.country if project.country %>
      <div class="horizontal-divider"></div>
    </li>
  <% end %>
  </ul>

  <% if user_signed_in? %>
      <%= link_to 'Add Project', new_project_path(), class: 'button', :style =>'float:center;' %>
  <% else %>
      <p style="text-align:center;"> Please register to add content to this page. </p>
  <% end %>
</div>

app/views/projects/new.html.erb
<p id="notice"><%= notice %></p>
<div class="border offset2 span10" >
<h2 style="text-align: center;">Add a New Project to Our Archive</h2>
<%= render 'form' %>
</div>

app/views/projects/show.html.erb
<div class="header_image" style="-webkit-filter: grayscale;-webkit-filter: brightness(60%);height:560px;overflow:hidden;z-index:0;">
<%= image_tag @project.main_image.url, :style => "min-width:1024px;" %>
</div>


<div class="offset2 span12" style="position:relative;margin-top:-500px;color:white;">
	<h3 style=""><%= @project.name %></h3>
		<p> Started <%= @project.created_at.to_date.to_formatted_s(:long)  %> , Last activity on <%= @project.updated_at.to_date.to_formatted_s(:long) %></p>
		<p>Tags: <%= @project.subject_tag if @project.subject_tag %></p>
`		<ul class="toc span3" style="color:white;">
			<h5>TABLE OF CONTENTS</h5>
			<li><a href="#community-partner">Community Partner</a></li>
			<li><a href="#problem-statement">Problem Statement</a></li>
			<li><a href="#current-documentation">Current Documentation</a></li>
			<li><a href="#active-tasks">Active Task List</a></li>
			<li><a href="#partner-organizations">Partner Organizations</a></li>
		</ul>
<div class="gray border offset7" style="z-index:0;background: rgba(0, 0, 0, .5);">
	<h4 style="text-align:center;"> Required Skills </h4>

	<div style="margin-left:80px;">
	<% @project.tasks.select("DISTINCT(SKILL)").each do |task| %>
		<li ><%= task.skill %></li>
	<% end %>
	</div>

	</br>
	<a href="#active-tasks" class="button">Contribute</a>
	</br>
	<p style="text-align:center;font-size:11px;"> (learn more to help out) </p>
	<%= link_to 'edit', edit_project_path(@project), :style => "margin-left:150px;" %>

</div>
<div style="position:absolute;left:850px;top:75px;z-index:999;">
	<%= image_tag User.find(@project.moderator_id).avatar.url(:thumb), :class => "img-circle" %>
</div>
</div>

<div style="position:absolute;left:50px;top:465px;z-index:999;">
	<%= image_tag @project.community_image.url(:medium), :class => "img-circle" %>
</div>

<div id="community-partner" style="height:250px;background-color:#fff;">
	<div class="offset5 span9" >
		<h3 style="text-align:center;"> Community Partner - <%= @project.city if @project.city %>, <%= @project.country if @project.country %></h3>
			<%= @project.community_overview %>
	</div>
</div>

<h2 style="text-align:center;margin-top:-15px;margin-bottom:30px;"><i>"<%= @project.quote %>"</i></h2>

<div id="problem-statement" style="height:250px;background-color:#fff;">
	<div class="offset2 span12" >
		<div class="span8">
			<h3 style="text-align:center;"> Problem Statement</h3>
			<%= @project.overview %>
			</div>
		<div class="span3">
		<%= image_tag @project.tech_image.url, :style => "height:200px;margin:15px;margin-top:45px;" if @project.tech_image %>
		</div>
</div>
	</div>
</div>

<div class="gray" id="current-documentation" style="width:100%;display:inline-block;white-space:nowrap;height:270px;background-color:#999;overflow-x:scroll;overflow-y:hidden;">
	<div class="doc" style="margin-top:20px;text-wrap:normal;">
		<h5 style="position:relative;padding-top:30px;margin-bottom:-45px;margin-left:50px;"> Document title</h5>
		<%= image_tag "/images/doc-icon.png", :style => "height:200px;" %>

		<% if @project.assets.present? %>
		<% @project.assets.each do |asset| %>
		<%= image_tag "/images/doc-icon.png", :style => "height:200px;" %>
		<% end %>
		<% else %>

		<% end %>

	</div>
	<a href="#" class="button">Add Document</a>

		<div class="offset2 span12" >
			<h3 style="text-align:center;">Current Documentation </h3>
<p> Have here a slideshow of document icon images each representing a document uploaded to the project (MVP) Have link in corner that creates modal window for uploading new documents. </p>
		<p>Adv: Display name on icon. When hover display rating and download button. Can send users to page listing all documents where communities can submit rating of the document and leave comments for it's improvement. </p>
		<p>Note: Since documents in this section can be rated and reviewed I hope that users will use it to store final documentation rather than working docs. May need to keep this in mind as developings site. </p>
	</div>
</div>

<div class="horizontal-divider"></div>

<div class="active-tasks" id="active-tasks" style="background-color:#fff;overflow:auto;">
	<div class="active-tasks offset2 span12" >
		<h3 style="text-align:center;"> Active Task List </h3>
			<table class="table table-striped">
			<thead>
				<td>Title</td>
				<td>Summary</td>
				<td>Skill</td>
				<td></td>
				<td></td>
			</thead>
				<% @project.tasks.each do |task| %>
				<tr>
					<td><%= task.title %></td>
				<td><%= task.summary %></td>
				<td><%= task.skill %></td>
				<td><%= link_to 'Close', project_task_path(@project, task), class: 'btn', :style =>'float: right' %>
				<td><%= link_to 'View', project_task_path(@project, task), class: 'btn', :style =>'float: right' %>
				</td>
				</tr>
			<% end %>
			</table>

		      <%= link_to 'Add Task', new_project_task_path(@project), class: 'button', :style =>'float: right' %>

	</div>
</div>

<div style="height:250px;background-color:#fff;display:none;">
<div class="offset2 span12">
<% if @project.assets.present? %>
<% @project.assets.each do |asset| %>
<p><%= link_to "Printable Case (PDF)", project_asset_path(@project, asset) %></p>
<% end %>
<% else %>
<p> There are no attachments for this project.</p>
<% end %>
<% if user_signed_in? %>
<%= render 'assets/documents_form' %>
<% end %>

<%= link_to 'Back', projects_path() %>
</div>
</div>


<div id="" style="height:150px;background-color:#69B4BD;display:none;">
	<div class="offset2 span12" >
		<h5 style="text-align:center;"> pitch to contribute to project</h5>
	</div>
</div>

<div id="partner-organizations" style="min-height:150px;background-color:#fff;">
	<div class="offset2 span12" >
		<% if @project.partner_organizations %>
		<p class="span2" style="margin-top:65px;text-align:left;"> SUPPORTED BY </p>
		<p  style="margin-top:65px;text-align:left;"> <%= @project.partner_organizations %></p>
		<% end %>

		<% if false %>
		<p style="margin-top:165px;text-align:center;">with contributors like you</p>
		<% end %>
	</div>
</div>