config/routes.rb
MakerSource::Application.routes.draw do
  authenticated :user do
    root :to => 'projects#index'
  end
  root :to => "projects#index"
  devise_for :users
    
    match '/users/:user_id/messages/inbox(/:id(.:format))', :controller => 'messages', :action => 'inbox', :via => [:get], :as => 'user_messages_inbox'
    match '/users/:user_id/messages/drafts(/:id(.:format))', :controller => 'messages', :action => 'drafts', :via => [:get], :as => 'user_messages_drafts'
    match '/users/:user_id/messages/sent(/:id(.:format))', :controller => 'messages', :action => 'sent', :via => [:get], :as => 'user_messages_sent'
    match '/users/:user_id/messages/archive(/:id(.:format))', :controller => 'messages', :action => 'archive', :via => [:get], :as => 'user_messages_archive'
    match '/users/:user_id/messages/trash(/:id(.:format))', :controller => 'messages', :action => 'trash', :via => [:get], :as => 'user_messages_trash'
    
    resources :users do
        resources :messages
        resources :contacts
    end
    resources :projects do
        resources :assets
        resources :tasks
    end
end

app/models/asset.rb
class Asset < ActiveRecord::Base
    belongs_to :project
 
    has_attached_file :document 
    attr_accessible :document

end

app/controllers/assets_controller.rb
class AssetsController < ApplicationController
    def show
        @project = Project.find(params[:project_id])
        @asset = @project.assets.find(params[:id])
    end
    
    def create
        @project = Project.find(params[:project_id])
        @asset = @project.assets.build(params[:asset])
        if @asset.save
            redirect_to project_path(@project)
        end
    end
end

app/views/assets/_documents_form.html.erb
<script>
$(document).ready(function() {
  $("#add_document").submit(function(event) {
    document.location.reload();
  });
  });
</script>

<%= simple_form_for(@project.assets.build, :url => project_assets_path(@project), :method => :post, :remote => true, :html => {:id => "add_document"} ) do |f| %>
  <%= f.error_notification %>

    <p> You can upload documents about this project below:</p>
<div class="form-inputs">    
    <div class="row">
    <div class="span1" style="width:100px;">Provide URL: </div>
    <div class="span3" style="width:100px;"><%=h f.input :document, :style=>"width:380px;" %></div> 
    </div>
</div>
<div class="form-actions">
    <span class="pull-right">
      <%= f.button :submit %>
    </span>
</div>
<% end %>